"""GENERATED by scripts/generate_session_routes.py — do not edit by hand.

Routes a per-user wallet session (the Apple session the iOS app holds) may
reach through the auth wall. Everything else that is not public stays behind
the operator key. Derived as: app-called paths ∩ gateway routes − exclusions.
"""
from __future__ import annotations

USER_SESSION_ROUTES: frozenset[str] = frozenset({
    "/api/v1/agent/register",
    "/api/v1/attestation/verify/{uid}",
    "/api/v1/auth/account",
    "/api/v1/auth/apple",
    "/api/v1/capabilities",
    "/api/v1/capabilities/categories",
    "/api/v1/capabilities/{capability_id}",
    "/api/v1/capabilities/{capability_id}/invoke",
    "/api/v1/contracts/convert",
    "/api/v1/dao/create",
    "/api/v1/dashboard/{address}",
    "/api/v1/defi/bridge/execute",
    "/api/v1/defi/bridge/quote",
    "/api/v1/defi/loan/create",
    "/api/v1/defi/loan/repay",
    "/api/v1/defi/swap/execute",
    "/api/v1/defi/swap/route",
    "/api/v1/dex/swap",
    "/api/v1/dispute/claim",
    "/api/v1/dispute/file",
    "/api/v1/dispute/vote",
    "/api/v1/fundraising/campaign/create",
    "/api/v1/fundraising/contribute",
    "/api/v1/gaming/register",
    "/api/v1/governance/daos/{daoId}/proposals",
    "/api/v1/governance/proposal/create",
    "/api/v1/governance/vote",
    "/api/v1/iap/verify",
    "/api/v1/identity/create",
    "/api/v1/identity/did/create",
    "/api/v1/identity/zk-proof/generate",
    "/api/v1/insurance/claim",
    "/api/v1/insurance/policy/create",
    "/api/v1/ip/register",
    "/api/v1/licensing/ip",
    "/api/v1/licensing/licenses",
    "/api/v1/loyalty/redeem",
    "/api/v1/marketplace/buy",
    "/api/v1/marketplace/list",
    "/api/v1/nft/mint",
    "/api/v1/oracle/price/{pair}",
    "/api/v1/paymaster/sign",
    "/api/v1/payments/create",
    "/api/v1/portfolio/complete/{wallet}",
    "/api/v1/portfolio/history/{wallet}",
    "/api/v1/portfolio/positions/{wallet}",
    "/api/v1/price/eth-usd",
    "/api/v1/rwa/listings",
    "/api/v1/rwa/tokenize",
    "/api/v1/securities/create",
    "/api/v1/security/preflight",
    "/api/v1/social/feed/{wallet}",
    "/api/v1/social/post",
    "/api/v1/stablecoin/transfer",
    "/api/v1/staking/stake",
    "/api/v1/staking/unstake",
    "/api/v1/subscriptions/subscribe",
    "/api/v1/supply-chain/register",
    "/bridge/v1/action",
    "/bridge/v1/chat",
    "/bridge/v1/components",
    "/bridge/v1/components/manifest",
    "/bridge/v1/components/{component_id}",
    "/bridge/v1/config",
    "/bridge/v1/dashboard",
    "/bridge/v1/push/register",
    "/bridge/v1/services",
    "/bridge/v1/session/create",
    "/bridge/v1/session/resume",
    "/bridge/v1/wallet/link",
    "/bridge/v1/wallet/status",
    "/health",
    "/security/appattest/attest",
    "/security/appattest/challenge",
    "/security/phone/request",
    "/security/phone/verify",
    "/social/actor/{wallet}",
    "/social/follow",
    "/social/unfollow",
    "/social/{address}/followers",
    "/social/{address}/following",
})

# Called by the app, present on the server, deliberately NOT session-reachable:
#   /memory/read — reads an AGENT's memory, shared across every user (register §D3.6)
#   /memory/write — writes an AGENT's memory, shared across every user (register §D3.6)
EXCLUDED_FROM_SESSION: frozenset[str] = frozenset({
    "/memory/read",
    "/memory/write",
})


def session_may_reach(canonical_route: str) -> bool:
    """True when a per-user session is a sufficient credential for this route.

    ``canonical_route`` is aiohttp's matched template
    (``request.match_info.route.resource.canonical``), e.g.
    ``/api/v1/portfolio/complete/{wallet}`` — exact membership, no prefix logic.
    """
    return (canonical_route.rstrip("/") or "/") in USER_SESSION_ROUTES
