apiVersion: v1
kind: Service
metadata:
  name: matrix-gateway
  namespace: the-matrix
  labels:
    app.kubernetes.io/name: matrix-gateway
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: matrix-gateway
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
