"""
RoyaltyEnforcement — configure and enforce royalties on IP usage.

Qualifying transaction types: sale, license, stream, download,
derivative, syndication.  Each type can have a different royalty
percentage.  Rights reversion attestation is TIME-CRITICAL
(via Component 8 / AttestationService).
"""

from __future__ import annotations

import logging
import time
import uuid
from typing import Any

logger = logging.getLogger(__name__)

USAGE_TYPES: set[str] = {
    "sale", "license", "stream", "download", "derivative", "syndication",
}

# Default royalty percentages by usage type
_DEFAULT_ROYALTIES: dict[str, float] = {
    "sale": 10.0,
    "license": 15.0,
    "stream": 5.0,
    "download": 8.0,
    "derivative": 12.0,
    "syndication": 10.0,
}


class RoyaltyEnforcement:
    """Enforces royalty rules on IP usage.

    Config keys (under ``config["ip_royalties"]``):
        default_royalties (dict): Per-type default royalty pct overrides.
    """

    def __init__(self, config: dict) -> None:
        self._config = config
        ip_cfg = config.get("ip_royalties", {})

        self._default_royalties: dict[str, float] = {
            **_DEFAULT_ROYALTIES,
            **ip_cfg.get("default_royalties", {}),
        }

        # ip_id -> royalty config
        self._configs: dict[str, dict[str, Any]] = {}
        # ip_id -> list of usage/royalty records
        self._history: dict[str, list[dict[str, Any]]] = {}

    async def configure_royalty(self, ip_id: str, rules: dict) -> dict:
        """Configure royalty rules for an IP asset.

        Args:
            ip_id: The IP asset.
            rules: Dict with per-usage-type percentages and optional
                   ``beneficiaries`` (list of {address, share_pct}).

        Returns:
            Configuration record.
        """
        royalty_rates: dict[str, float] = {}
        for usage_type in USAGE_TYPES:
            royalty_rates[usage_type] = float(
                rules.get(usage_type, self._default_royalties.get(usage_type, 10.0))
            )

        beneficiaries = rules.get("beneficiaries", [])
        if beneficiaries:
            total_share = sum(float(b.get("share_pct", 0)) for b in beneficiaries)
            if abs(total_share - 100.0) > 0.01:
                raise ValueError(
                    f"Beneficiary shares must sum to 100, got {total_share}"
                )

        config: dict[str, Any] = {
            "ip_id": ip_id,
            "royalty_rates": royalty_rates,
            "beneficiaries": beneficiaries,
            "configured_at": int(time.time()),
        }
        self._configs[ip_id] = config

        logger.info("Royalty configured: ip=%s rates=%s", ip_id, royalty_rates)
        return config

    async def get_config(self, ip_id: str) -> dict:
        """Get the royalty configuration for an IP asset."""
        return self._configs.get(ip_id, {
            "ip_id": ip_id,
            "royalty_rates": dict(self._default_royalties),
            "beneficiaries": [],
            "configured_at": None,
        })

    async def process_usage(
        self, ip_id: str, usage_type: str, revenue: float,
    ) -> dict:
        """Process a usage event and calculate royalties.

        Args:
            ip_id: The IP being used.
            usage_type: One of the qualifying transaction types.
            revenue: Revenue generated by this usage.

        Returns:
            Royalty record with amounts per beneficiary.
        """
        if usage_type not in USAGE_TYPES:
            raise ValueError(
                f"Unknown usage_type '{usage_type}'. "
                f"Must be one of: {', '.join(sorted(USAGE_TYPES))}"
            )
        if revenue <= 0:
            raise ValueError("Revenue must be positive")

        config = self._configs.get(ip_id)
        if not config:
            # Use defaults
            config = {
                "royalty_rates": dict(self._default_royalties),
                "beneficiaries": [],
            }

        rate = config["royalty_rates"].get(usage_type, 10.0)
        royalty_amount = revenue * (rate / 100.0)

        # Distribute among beneficiaries
        beneficiaries = config.get("beneficiaries", [])
        payouts: list[dict[str, Any]] = []

        if beneficiaries:
            for b in beneficiaries:
                share = float(b.get("share_pct", 0))
                amount = royalty_amount * (share / 100.0)
                payouts.append({
                    "address": b["address"],
                    "amount": round(amount, 6),
                    "share_pct": share,
                })
        else:
            # No beneficiaries configured; full royalty to be claimed
            payouts.append({
                "address": "unclaimed",
                "amount": round(royalty_amount, 6),
                "share_pct": 100.0,
            })

        record_id = f"usage_{uuid.uuid4().hex[:12]}"
        record: dict[str, Any] = {
            "record_id": record_id,
            "ip_id": ip_id,
            "usage_type": usage_type,
            "revenue": revenue,
            "royalty_rate_pct": rate,
            "royalty_amount": round(royalty_amount, 6),
            "payouts": payouts,
            "timestamp": int(time.time()),
        }
        self._history.setdefault(ip_id, []).append(record)

        # Attest rights-reversion events as TIME-CRITICAL via Component 8
        if usage_type in ("derivative", "syndication"):
            await self._attest_rights_reversion(ip_id, record)

        logger.info(
            "Usage processed: ip=%s type=%s revenue=%.6f royalty=%.6f",
            ip_id, usage_type, revenue, royalty_amount,
        )
        return record

    async def get_royalty_history(self, ip_id: str) -> list:
        """Get all royalty/usage records for an IP asset."""
        return self._history.get(ip_id, [])

    # ------------------------------------------------------------------
    # Attestation
    # ------------------------------------------------------------------

    async def _attest_rights_reversion(
        self, ip_id: str, record: dict,
    ) -> None:
        """Attest rights-reversion-relevant usage as TIME-CRITICAL."""
        try:
            from runtime.blockchain.services.attestation import AttestationService

            svc = AttestationService(self._config)
            await svc.attest(
                schema_uid="primary",
                data={
                    "action": "rights_reversion_usage",
                    "category": "rights_reversion",
                    "ip_id": ip_id,
                    "usage_type": record["usage_type"],
                    "royalty_amount": record["royalty_amount"],
                },
                recipient=self._config.get("blockchain", {}).get(
                    "platform_wallet", ""
                ),
                time_critical=True,
            )
        except ImportError:
            logger.debug("AttestationService not available; skipping.")
        except Exception as exc:
            logger.warning("Rights reversion attestation failed: %s", exc)
