#!/usr/bin/env python3
"""Generate gateway/session_routes.py — the routes a per-user session may reach.

T2 / path A (Matrix register entry::D005-DECIDED-A): the auth wall accepts the
Apple session the iOS app holds as a credential ONLY on the routes the app
actually calls. Anything else stays behind the operator key. The list is
derived, not hand-written:

    app-called paths  (string literals after `path:` / `endpoint:` in the
                       MTRX client, `\\(x)` interpolations → `{}`)
  ∩ gateway routes   (docs/ROUTES.md, `{name}` params → `{}`)
  − exclusions       (routes that exist and are called but must NOT open to a
                       user session, each with its reason)

Under-inclusion shows up as a 401 on a feature (visible); over-inclusion would
be a silent privilege grant — so the derivation errs toward the former.

Usage:
    python3 scripts/generate_session_routes.py [--client PATH] [--check]

The generated module is committed; CI needs no MTRX checkout. `--check` exits 1
when the committed module differs from what the inputs produce.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ROUTES_MD = ROOT / "docs" / "ROUTES.md"
OUT = ROOT / "gateway" / "session_routes.py"
# The whole app tree (minus its tests): MTRXAPIClient.swift carries nearly every
# call, but five component files reach the gateway on their own.
DEFAULT_CLIENT = ROOT.parent / "MTRX"

# Routes the app calls that a user session must NOT unlock, with the reason.
EXCLUDED = {
    "/memory/read": "reads an AGENT's memory, shared across every user (register §D3.6)",
    "/memory/write": "writes an AGENT's memory, shared across every user (register §D3.6)",
}

_LITERAL = re.compile(r'(?:path|endpoint):\s*"([^"]+)"')
_INTERP = re.compile(r"\\\([^)]*\)")
_PARAM = re.compile(r"\{[^}]*\}")
_ROUTE_ROW = re.compile(r"^\|\s*(GET|POST|PUT|DELETE|PATCH)\s*\|\s*`?(/[^\s`|]*)")


def _swift_sources(client: Path):
    if client.is_file():
        return [client]
    return sorted(f for f in client.rglob("*.swift") if "/Tests/" not in f.as_posix())


def app_paths(client: Path) -> set[str]:
    out = set()
    for f in _swift_sources(client):
        text = f.read_text(encoding="utf-8", errors="replace")
        for lit in _LITERAL.findall(text):
            p = _INTERP.sub("{}", lit)
            p = p.split("?", 1)[0]
            out.add(p.rstrip("/") or "/")
    return out


def gateway_routes(routes_md: Path) -> dict[str, str]:
    """canonical route template → normalised (`{name}` → `{}`)."""
    out = {}
    for line in routes_md.read_text(encoding="utf-8").splitlines():
        m = _ROUTE_ROW.match(line)
        if not m:
            continue
        canonical = m.group(2).rstrip("/") or "/"
        out[canonical] = _PARAM.sub("{}", canonical)
    return out


def derive(client: Path, routes_md: Path):
    called = app_paths(client)
    routes = gateway_routes(routes_md)
    allowed, excluded = [], []
    for canonical, normalised in sorted(routes.items()):
        if normalised not in called:
            continue
        if canonical in EXCLUDED:
            excluded.append(canonical)
            continue
        allowed.append(canonical)
    return allowed, excluded, len(called), len(routes)


def render(allowed, excluded) -> str:
    lines = [
        '"""GENERATED by scripts/generate_session_routes.py — do not edit by hand.',
        "",
        "Routes a per-user wallet session (the Apple session the iOS app holds) may",
        "reach through the auth wall. Everything else that is not public stays behind",
        "the operator key. Derived as: app-called paths ∩ gateway routes − exclusions.",
        '"""',
        "from __future__ import annotations",
        "",
        "USER_SESSION_ROUTES: frozenset[str] = frozenset({",
    ]
    lines += [f'    "{p}",' for p in allowed]
    lines += ["})", "", "# Called by the app, present on the server, deliberately NOT session-reachable:"]
    lines += [f"#   {p} — {EXCLUDED[p]}" for p in excluded]
    lines += [
        "EXCLUDED_FROM_SESSION: frozenset[str] = frozenset({",
    ]
    lines += [f'    "{p}",' for p in excluded]
    lines += [
        "})",
        "",
        "",
        "def session_may_reach(canonical_route: str) -> bool:",
        '    """True when a per-user session is a sufficient credential for this route.',
        "",
        "    ``canonical_route`` is aiohttp's matched template",
        "    (``request.match_info.route.resource.canonical``), e.g.",
        '    ``/api/v1/portfolio/complete/{wallet}`` — exact membership, no prefix logic.',
        '    """',
        '    return (canonical_route.rstrip("/") or "/") in USER_SESSION_ROUTES',
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--client", type=Path, default=DEFAULT_CLIENT)
    ap.add_argument("--routes", type=Path, default=ROUTES_MD)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    if not a.client.exists():
        print(f"client not found: {a.client}", file=sys.stderr)
        return 2
    allowed, excluded, n_called, n_routes = derive(a.client, a.routes)
    text = render(allowed, excluded)
    if a.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("gateway/session_routes.py is stale — regenerate", file=sys.stderr)
            return 1
        print(f"up to date: {len(allowed)} session routes, {len(excluded)} excluded")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(allowed)} session routes "
          f"(app paths {n_called} ∩ gateway routes {n_routes}) · excluded {len(excluded)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
