#!/usr/bin/env bash
# Re-hash the dependency locks after changing a pin.
#
#   scripts/relock_requirements.sh
#
# requirements.txt and requirements-build.txt are hashed locks: every pin is
# `==`, every file pip may download for it carries a --hash, and pip refuses
# anything else. Edit a version in place (its hash lines are then stale), run
# this, and review the diff. It keeps every pin you wrote, markers included,
# re-resolves only what a changed pin newly needs, and regenerates every hash
# from PyPI. The header of each file (everything down to its GENERATED line)
# is kept as written.
#
# --universal resolves for every interpreter from the floor up and every
# platform, so a backport only an older Python needs (async-timeout and
# exceptiongroup on 3.10) is locked under its marker rather than left free.
#
# Needs uv (https://docs.astral.sh/uv/) and network access to PyPI.
set -euo pipefail

cd "$(dirname "$0")/.."
command -v uv >/dev/null 2>&1 || { echo "relock: needs uv — https://docs.astral.sh/uv/" >&2; exit 1; }

MARK="# ── GENERATED by scripts/relock_requirements.sh"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

relock() {
    local file="$1" floor="$2"
    grep -qF "$MARK" "$file" || { echo "relock: $file has no GENERATED line" >&2; exit 1; }
    # The pins as written: requirement lines only, without the trailing
    # continuation backslash and without the hash lines under them.
    grep -E '^[A-Za-z0-9]' "$file" | sed -E 's/[[:space:]]*\\$//' > "$tmp/in.txt"
    {
        awk -v mark="$MARK" '{ print } index($0, mark) == 1 { exit }' "$file"
        uv pip compile "$tmp/in.txt" \
            --universal --python-version "$floor" \
            --generate-hashes --no-header --no-annotate --quiet
    } > "$tmp/out.txt"
    mv "$tmp/out.txt" "$file"
    echo "relocked $file"
}

relock requirements.txt 3.10
relock requirements-build.txt 3.11
